@startuml

state "Подключение к устройствам" as device_connect
state "Сброс парамметров устройств" as reset_devices
state "Установка параметров устройств" as set_devices
state "Установка параметров калибратора" as set_calibrator

state "Получение параметров ячейки" as get_cell_params
state "Ожидание выхода на режим" as wait_ready
state "Измерение выходного значения калибратора" as measurement
state "Рассчет параметров измерения" as calc_parameters
state "Прошивка в калибратор" as flash_data
state "Следующее измерение" as next_measure
state "Окончание измерения" as measure_finish
state "Вывод ошибок" as errors_output


[*] --> device_connect
device_connect --> get_cell_params
get_cell_params --> reset_devices
reset_devices: В это состояние можно перейти почти из любого другого \
\nсостояния, если пользователь нажмет кнопку СТОП
reset_devices --> set_devices
set_devices --> set_calibrator
set_calibrator --> wait_ready
set_calibrator --> errors_output: "Ошибка калиб."
wait_ready --> measurement
wait_ready --> errors_output: "Ошибка калиб."
measurement --> calc_parameters
measurement --> errors_output: "Ошибка калиб."
errors_output --> set_calibrator
calc_parameters --> flash_data
calc_parameters --> next_measure
flash_data --> next_measure
next_measure --> reset_devices
next_measure --> get_cell_params
reset_devices --> measure_finish
measure_finish --> [*]

@enduml
