@startuml

state "Подключение к устройствам" as device_connect
state "Сброс парамметров устройств" as reset_devices
state "Установка параметров устройств" as set_devices

state "Получение параметров ячейки" as get_cell_params
state "Ожидание выхода на режим" as wait_ready
state "Измерение выходного значения калибратора" as measurement
state "Рассчет параметров измерения" as calc_parameters
state "Прошивка в калибратор" as flash_data
state "Следующее измерение" as next_measure
state "Окончание измерения" as measure_finish


[*] --> device_connect
device_connect --> reset_devices
reset_devices --> get_cell_params
get_cell_params --> set_devices
set_devices --> wait_ready
wait_ready --> measurement
measurement --> calc_parameters
calc_parameters --> flash_data
calc_parameters --> next_measure
flash_data --> next_measure
next_measure --> reset_devices
reset_devices --> measure_finish
measure_finish --> [*]

@enduml