# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/correction_tables_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_correction_tables_dialog(object):
    def setupUi(self, correction_tables_dialog):
        correction_tables_dialog.setObjectName("correction_tables_dialog")
        correction_tables_dialog.resize(669, 461)
        font = QtGui.QFont()
        font.setPointSize(10)
        correction_tables_dialog.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/graph_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        correction_tables_dialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(correction_tables_dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.correction_tables_splitter = QtWidgets.QSplitter(correction_tables_dialog)
        self.correction_tables_splitter.setOrientation(QtCore.Qt.Horizontal)
        self.correction_tables_splitter.setObjectName("correction_tables_splitter")
        self.layoutWidget = QtWidgets.QWidget(self.correction_tables_splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_names_list = QtWidgets.QListWidget(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_names_list.setFont(font)
        self.table_names_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.table_names_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_names_list.setAlternatingRowColors(True)
        self.table_names_list.setObjectName("table_names_list")
        self.verticalLayout.addWidget(self.table_names_list)
        self.save_to_file_button = QtWidgets.QPushButton(self.layoutWidget)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.verticalLayout.addWidget(self.save_to_file_button)
        self.correction_table_view = QtWidgets.QTableView(self.correction_tables_splitter)
        self.correction_table_view.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.correction_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.correction_table_view.setAlternatingRowColors(False)
        self.correction_table_view.setObjectName("correction_table_view")
        self.correction_table_view.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.correction_tables_splitter, 0, 0, 1, 1)
        self.copy_cell_value_action = QtWidgets.QAction(correction_tables_dialog)
        self.copy_cell_value_action.setObjectName("copy_cell_value_action")
        self.copy_table_to_measure_action = QtWidgets.QAction(correction_tables_dialog)
        self.copy_table_to_measure_action.setObjectName("copy_table_to_measure_action")

        self.retranslateUi(correction_tables_dialog)
        QtCore.QMetaObject.connectSlotsByName(correction_tables_dialog)

    def retranslateUi(self, correction_tables_dialog):
        _translate = QtCore.QCoreApplication.translate
        correction_tables_dialog.setWindowTitle(_translate("correction_tables_dialog", "Таблицы коррекции"))
        self.save_to_file_button.setText(_translate("correction_tables_dialog", "Сохранить в файл"))
        self.copy_cell_value_action.setText(_translate("correction_tables_dialog", "Копировать значение"))
        self.copy_cell_value_action.setShortcut(_translate("correction_tables_dialog", "Ctrl+C"))
        self.copy_table_to_measure_action.setText(_translate("correction_tables_dialog", "Копировать в измерение"))
import icons_rc
