# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/graph_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tstlan_graphs_dialog(object):
    def setupUi(self, tstlan_graphs_dialog):
        tstlan_graphs_dialog.setObjectName("tstlan_graphs_dialog")
        tstlan_graphs_dialog.resize(838, 554)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/graph_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        tstlan_graphs_dialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(tstlan_graphs_dialog)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(tstlan_graphs_dialog)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(tstlan_graphs_dialog)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.chart_layout = QtWidgets.QHBoxLayout()
        self.chart_layout.setObjectName("chart_layout")
        self.verticalLayout.addLayout(self.chart_layout)

        self.retranslateUi(tstlan_graphs_dialog)
        QtCore.QMetaObject.connectSlotsByName(tstlan_graphs_dialog)

    def retranslateUi(self, tstlan_graphs_dialog):
        _translate = QtCore.QCoreApplication.translate
        tstlan_graphs_dialog.setWindowTitle(_translate("tstlan_graphs_dialog", "Графики tstlan"))
        self.pushButton.setText(_translate("tstlan_graphs_dialog", "Параметры"))
import icons_rc
